package c

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/tomiya7688/neo-Cobol/internal/nir"
	"github.com/tomiya7688/neo-Cobol/internal/types"
)

func Emit(program *nir.Program) (string, error) {
	var b strings.Builder
	b.WriteString("/* Generated by neoc. Do not edit. */\n")
	b.WriteString("#include <stdbool.h>\n#include <stdint.h>\n#include <inttypes.h>\n#include <stdio.h>\n#include <string.h>\n\n")
	b.WriteString("int main(void) {\n")
	cNames := make(map[string]string, len(program.Variables))
	nextID := 0
	for _, variable := range program.Variables {
		cName := fmt.Sprintf("neo_v_%d", nextID)
		nextID++
		cNames[variable.Name] = cName
		cType, err := cType(variable.Type.Kind)
		if err != nil {
			return "", fmt.Errorf("variable %s: %w", variable.Name, err)
		}
		initial := defaultValue(variable.Type.Kind)
		if variable.Initial != nil {
			initial, err = emitValue(*variable.Initial, cNames)
			if err != nil {
				return "", err
			}
		}
		fmt.Fprintf(&b, "    %s %s = %s;\n", cType, cName, initial)
	}
	if len(program.Variables) > 0 {
		b.WriteByte('\n')
	}
	if err := emitOps(&b, program.Ops, cNames, &nextID, 1); err != nil {
		return "", err
	}
	b.WriteString("    return 0;\n}\n")
	return b.String(), nil
}
func emitOps(b *strings.Builder, ops []nir.Op, cNames map[string]string, nextID *int, indent int) error {
	pad := strings.Repeat("    ", indent)
	for _, operation := range ops {
		switch op := operation.(type) {
		case nir.Declare:
			if _, exists := cNames[op.Name]; exists {
				return fmt.Errorf("C backend duplicate variable %s", op.Name)
			}
			initial, err := emitValue(op.Initial, cNames)
			if err != nil {
				return err
			}
			declType, err := cType(op.Type.Kind)
			if err != nil {
				return fmt.Errorf("binding %s: %w", op.Name, err)
			}
			cName := fmt.Sprintf("neo_v_%d", *nextID)
			*nextID++
			cNames[op.Name] = cName
			fmt.Fprintf(b, "%s%s %s = %s;\n", pad, declType, cName, initial)
		case nir.Display:
			for _, value := range op.Values {
				if err := emitDisplay(b, value, cNames, pad); err != nil {
					return err
				}
			}
			fmt.Fprintf(b, "%sfputc('\\n', stdout);\n", pad)
		case nir.Move:
			target, ok := cNames[op.Target]
			if !ok {
				return fmt.Errorf("C backend missing target %s", op.Target)
			}
			source, err := emitValue(op.Source, cNames)
			if err != nil {
				return err
			}
			fmt.Fprintf(b, "%s%s = %s;\n", pad, target, source)
		case nir.If:
			condition, err := emitCondition(op.Condition, cNames)
			if err != nil {
				return err
			}
			fmt.Fprintf(b, "%sif (%s) {\n", pad, condition)
			if err := emitOps(b, op.Then, cNames, nextID, indent+1); err != nil {
				return err
			}
			fmt.Fprintf(b, "%s}", pad)
			if len(op.Else) > 0 {
				b.WriteString(" else {\n")
				if err := emitOps(b, op.Else, cNames, nextID, indent+1); err != nil {
					return err
				}
				fmt.Fprintf(b, "%s}\n", pad)
			} else {
				b.WriteByte('\n')
			}
		default:
			return fmt.Errorf("C backend does not support NIR op %T", operation)
		}
	}
	return nil
}
func emitCondition(condition nir.Condition, cNames map[string]string) (string, error) {
	switch cond := condition.(type) {
	case nir.Truth:
		return emitValue(cond.Value, cNames)
	case nir.Not:
		inner, err := emitCondition(cond.Inner, cNames)
		if err != nil {
			return "", err
		}
		return "!(" + inner + ")", nil
	case nir.Logical:
		left, err := emitCondition(cond.Left, cNames)
		if err != nil {
			return "", err
		}
		right, err := emitCondition(cond.Right, cNames)
		if err != nil {
			return "", err
		}
		op := "&&"
		if cond.Op == nir.LogicalOr {
			op = "||"
		}
		return fmt.Sprintf("(%s) %s (%s)", left, op, right), nil
	case nir.Compare:
		left, err := emitValue(cond.Left, cNames)
		if err != nil {
			return "", err
		}
		right, err := emitValue(cond.Right, cNames)
		if err != nil {
			return "", err
		}
		if cond.Left.Type == types.String && cond.Right.Type == types.String {
			switch cond.Op {
			case nir.CompareEqual:
				return fmt.Sprintf("strcmp(%s, %s) == 0", left, right), nil
			case nir.CompareNotEqual:
				return fmt.Sprintf("strcmp(%s, %s) != 0", left, right), nil
			default:
				return "", fmt.Errorf("ordered STRING comparison reached C backend")
			}
		}
		operator := "=="
		switch cond.Op {
		case nir.CompareEqual:
			operator = "=="
		case nir.CompareNotEqual:
			operator = "!="
		case nir.CompareGreater:
			operator = ">"
		case nir.CompareLess:
			operator = "<"
		case nir.CompareGreaterEqual:
			operator = ">="
		case nir.CompareLessEqual:
			operator = "<="
		}
		return fmt.Sprintf("(%s) %s (%s)", left, operator, right), nil
	default:
		return "", fmt.Errorf("C backend does not support condition %T", condition)
	}
}
func cType(kind types.Kind) (string, error) {
	switch kind {
	case types.String:
		return "const char *", nil
	case types.Boolean:
		return "bool", nil
	case types.Byte:
		return "uint8_t", nil
	case types.Integer:
		return "int32_t", nil
	case types.Long:
		return "int64_t", nil
	case types.Float:
		return "float", nil
	case types.Double:
		return "double", nil
	case types.Decimal:
		return "", fmt.Errorf("DECIMAL lowering is not implemented by the C11 backend yet")
	default:
		return "", fmt.Errorf("unsupported type %s", kind)
	}
}
func defaultValue(kind types.Kind) string {
	switch kind {
	case types.String:
		return "NULL"
	case types.Boolean:
		return "false"
	default:
		return "0"
	}
}
func emitValue(value nir.Value, cNames map[string]string) (string, error) {
	if value.Kind == nir.VariableValue {
		name, ok := cNames[value.Text]
		if !ok {
			return "", fmt.Errorf("C backend missing variable %s", value.Text)
		}
		return name, nil
	}
	switch value.Type {
	case types.String:
		return strconv.Quote(value.Text), nil
	case types.Boolean:
		if value.Text == "TRUE" {
			return "true", nil
		}
		return "false", nil
	case types.Byte, types.Integer, types.Long:
		parsed, err := strconv.ParseInt(value.Text, 0, 64)
		if err != nil {
			return "", fmt.Errorf("invalid integer literal %q: %w", value.Text, err)
		}
		return strconv.FormatInt(parsed, 10), nil
	case types.Decimal:
		return "", fmt.Errorf("DECIMAL literal lowering is not implemented by the C11 backend yet")
	default:
		return "", fmt.Errorf("cannot emit literal of type %s", value.Type)
	}
}
func emitDisplay(b *strings.Builder, value nir.Value, cNames map[string]string, pad string) error {
	expr, err := emitValue(value, cNames)
	if err != nil {
		return err
	}
	switch value.Type {
	case types.String:
		fmt.Fprintf(b, "%sfputs(%s, stdout);\n", pad, expr)
	case types.Boolean:
		fmt.Fprintf(b, "%sfputs((%s) ? \"TRUE\" : \"FALSE\", stdout);\n", pad, expr)
	case types.Byte:
		fmt.Fprintf(b, "%sprintf(\"%%u\", (unsigned)(%s));\n", pad, expr)
	case types.Integer:
		fmt.Fprintf(b, "%sprintf(\"%%\" PRId32, (int32_t)(%s));\n", pad, expr)
	case types.Long:
		fmt.Fprintf(b, "%sprintf(\"%%\" PRId64, (int64_t)(%s));\n", pad, expr)
	default:
		return fmt.Errorf("DISPLAY lowering is not implemented for %s", value.Type)
	}
	return nil
}
