package c

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/tomiya7688/neo-Cobol/internal/nir"
)

// Emit renders Neo IR as portable C11. The bootstrap backend uses libc
// directly; runtime/c is reserved for behavior that needs shared runtime code.
func Emit(program *nir.Program) (string, error) {
	var b strings.Builder
	b.WriteString("/* Generated by neoc. Do not edit. */\n")
	b.WriteString("#include <stdio.h>\n\n")
	b.WriteString("int main(void) {\n")
	for _, operation := range program.Ops {
		switch op := operation.(type) {
		case nir.Display:
			for _, value := range op.Values {
				fmt.Fprintf(&b, "    fputs(%s, stdout);\n", strconv.Quote(value))
			}
			b.WriteString("    fputc('\\n', stdout);\n")
		default:
			return "", fmt.Errorf("C backend does not support NIR op %T", operation)
		}
	}
	b.WriteString("    return 0;\n")
	b.WriteString("}\n")
	return b.String(), nil
}
