package c

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/tomiya7688/neo-Cobol/internal/nir"
	"github.com/tomiya7688/neo-Cobol/internal/types"
)

func Emit(program *nir.Program) (string, error) {
	var b strings.Builder
	b.WriteString("/* Generated by neoc. Do not edit. */\n")
	b.WriteString("#include <stdbool.h>\n#include <stdint.h>\n#include <inttypes.h>\n#include <stdio.h>\n\n")
	b.WriteString("int main(void) {\n")

	cNames := make(map[string]string, len(program.Variables))
	for i, variable := range program.Variables {
		cName := fmt.Sprintf("neo_v_%d", i)
		cNames[variable.Name] = cName
		cType, err := cType(variable.Type.Kind)
		if err != nil {
			return "", fmt.Errorf("variable %s: %w", variable.Name, err)
		}
		initial := defaultValue(variable.Type.Kind)
		if variable.Initial != nil {
			initial, err = emitValue(*variable.Initial, cNames)
			if err != nil {
				return "", err
			}
		}
		fmt.Fprintf(&b, "    %s %s = %s;\n", cType, cName, initial)
	}
	if len(program.Variables) > 0 {
		b.WriteByte('\n')
	}

	for _, operation := range program.Ops {
		switch op := operation.(type) {
		case nir.Display:
			for _, value := range op.Values {
				if err := emitDisplay(&b, value, cNames); err != nil {
					return "", err
				}
			}
			b.WriteString("    fputc('\\n', stdout);\n")
		case nir.Move:
			target, ok := cNames[op.Target]
			if !ok {
				return "", fmt.Errorf("C backend missing target %s", op.Target)
			}
			source, err := emitValue(op.Source, cNames)
			if err != nil {
				return "", err
			}
			fmt.Fprintf(&b, "    %s = %s;\n", target, source)
		default:
			return "", fmt.Errorf("C backend does not support NIR op %T", operation)
		}
	}
	b.WriteString("    return 0;\n}\n")
	return b.String(), nil
}

func cType(kind types.Kind) (string, error) {
	switch kind {
	case types.String:
		return "const char *", nil
	case types.Boolean:
		return "bool", nil
	case types.Byte:
		return "uint8_t", nil
	case types.Integer:
		return "int32_t", nil
	case types.Long:
		return "int64_t", nil
	case types.Float:
		return "float", nil
	case types.Double:
		return "double", nil
	case types.Decimal:
		return "", fmt.Errorf("DECIMAL lowering is not implemented by the C11 backend yet")
	default:
		return "", fmt.Errorf("unsupported type %s", kind)
	}
}

func defaultValue(kind types.Kind) string {
	switch kind {
	case types.String:
		return "NULL"
	case types.Boolean:
		return "false"
	default:
		return "0"
	}
}

func emitValue(value nir.Value, cNames map[string]string) (string, error) {
	if value.Kind == nir.VariableValue {
		name, ok := cNames[value.Text]
		if !ok {
			return "", fmt.Errorf("C backend missing variable %s", value.Text)
		}
		return name, nil
	}
	switch value.Type {
	case types.String:
		return strconv.Quote(value.Text), nil
	case types.Boolean:
		if value.Text == "TRUE" {
			return "true", nil
		}
		return "false", nil
	case types.Byte, types.Integer, types.Long:
		parsed, err := strconv.ParseInt(value.Text, 0, 64)
		if err != nil {
			return "", fmt.Errorf("invalid integer literal %q: %w", value.Text, err)
		}
		return strconv.FormatInt(parsed, 10), nil
	case types.Decimal:
		return "", fmt.Errorf("DECIMAL literal lowering is not implemented by the C11 backend yet")
	default:
		return "", fmt.Errorf("cannot emit literal of type %s", value.Type)
	}
}

func emitDisplay(b *strings.Builder, value nir.Value, cNames map[string]string) error {
	expr, err := emitValue(value, cNames)
	if err != nil {
		return err
	}
	switch value.Type {
	case types.String:
		fmt.Fprintf(b, "    fputs(%s, stdout);\n", expr)
	case types.Boolean:
		fmt.Fprintf(b, "    fputs((%s) ? \"TRUE\" : \"FALSE\", stdout);\n", expr)
	case types.Byte:
		fmt.Fprintf(b, "    printf(\"%%u\", (unsigned)(%s));\n", expr)
	case types.Integer:
		fmt.Fprintf(b, "    printf(\"%%\" PRId32, (int32_t)(%s));\n", expr)
	case types.Long:
		fmt.Fprintf(b, "    printf(\"%%\" PRId64, (int64_t)(%s));\n", expr)
	default:
		return fmt.Errorf("DISPLAY lowering is not implemented for %s", value.Type)
	}
	return nil
}
